### ISSUE TITLE
Horários com 3 horas adiantadas

### ISSUE THREAD

**Issue by luancerilio** [marcelojrfarias/Calengrade#1]
![image](https://user-images.githubusercontent.com/44935261/71740216-65419880-2e3a-11ea-8a12-2798c9d0755e.png)

ESTO903-17 - Engenharia Unificada II A1-Noturno (Santo André) - TPI (0 - 2 - 5) - Campus Santo André
Terça-feira das 19:00 às 21:00 - semanal
ESTA004-17 - Circuitos Elétricos II A1-Noturno (Santo André) - TPI (3 - 2 - 4) - Campus Santo André
Quarta-feira das 18:00 às 21:00 - semanal
Segunda-feira das 21:00 às 23:00 - quinzenal (I)
Segunda-feira das 21:00 às 23:00 - quinzenal (II)
ESTI010-17 - Comunicações Ópticas A-Noturno (Santo André) - TPI (3 - 1 - 4) - Campus Santo André
Terça-feira das 21:00 às 23:00 - quinzenal (II)
Quinta-feira das 19:00 às 21:00 - semanal
Terça-feira das 21:00 às 23:00 - quinzenal (I)
ESTI018-17 - Ondas Eletromagnéticas Aplicadas A-Matutino (Santo André) - TPI (3 - 1 - 4) - Campus Santo André
Terça-feira das 08:00 às 10:00 - quinzenal (I)
Sexta-feira das 10:00 às 12:00 - semanal
Terça-feira das 08:00 às 10:00 - quinzenal (II)
ESTI008-17 - Teoria da Informação e Códigos A-Noturno (Santo André) - TPI (4 - 0 - 4) - Campus Santo André
Quinta-feira das 21:00 às 23:00 - semanal
Segunda-feira das 19:00 às 21:00 - semanal

**Comment by marcelojrfarias** [comment]
Olá, Luan! Obrigado por contribuir com seu feedback :)

Realmente havia um problema com relação a uma diferença entre a hora do servidor e a hora do seu browser. Fiz algumas alterações e o problema deve ter sido corrigido. Peço que faça um teste novamente e me avise se tudo correr bem.

**Comment by luancerilio** [comment]
Olá Marcelo.
Testei novamente e aparentemente o problema foi resolvido, apesar de não estar na mesma máquina/rede anteriores. Segunda-feira testarei novamente, assim terei certeza.
