### ISSUE TITLE
Erro em uma matéria e não foi pro quadrimestre inteiro

### ISSUE THREAD

**Issue by gustassou** [marcelojrfarias/Calengrade#15]
Tive dois problemas: 
O site não reconheceu a disciplina "Filosofia da Ciência: em torno à concepção ortodoxa", somente "em torno à concepção ortodoxa". Além disso, ele só gerou do dia 10 até o dia 14 de fevereiro, mesmo sem eu ter mudado a configuração de data do site. 

Atenciosamente,
Gustavo Severo Souza

![ea918cb3-ee24-4e4f-8a89-64764820cba3](https://user-images.githubusercontent.com/60679837/73805336-31dd8b00-47a5-11ea-9e6c-b462889bca3f.jpg)

**Comment by gustassou** [comment]
Tentei em outro app de agenda e o mesmo erro ocorreu.

**Comment by gustassou** [comment]
BHS0001-15 - Práticas em Ciências e Humanidades A2-Noturno (São Bernardo) - TPI (2 - 2 - 4) - Campus São Bernardo do Campo
Terça-feira das 19:00 às 21:00 - semanal
Quinta-feira das 21:00 às 23:00 - semanal
MCZC011-15 - Tomada de Decisões e Neuroeconomia A-Noturno (São Bernardo) - TPI (4 - 0 - 4) - Campus São Bernardo do Campo
Segunda-feira das 19:00 às 21:00 - semanal
Quarta-feira das 21:00 às 23:00 - semanal
NHH2015-13 - Filosofia da Ciência: em torno à concepção ortodoxa A-Noturno (São Bernardo) - TPI (4 - 0 - 4) - Campus São Bernardo do Campo
Quinta-feira das 19:00 às 21:00 - semanal
Segunda-feira das 21:00 às 23:00 - semanal
MCTC014-13 - Introdução à Inferência Estatística A3-Noturno (São Bernardo) - TPI (3 - 1 - 4) - Campus São Bernardo do Campo
Quarta-feira das 19:00 às 21:00 - semanal
Sexta-feira das 21:00 às 23:00 - semanal

**Comment by gustassou** [comment]
Ai está meu resumo para testes

**Comment by marcelojrfarias** [comment]
Olá, Gustavo! Obrigado pela sua contribuição :)

Primeiro, sugiro que você remova seu número de celular, pois qualquer pessoa pode obtê-lo por aqui, não é um local de acesso restrito.

Quanto ao fato de parecer que ele só adicionou disciplinas do 10 até o dia 14 de fevereiro, na verdade é que ele criou os eventos das aulas na primeira semana, mas com uma regra de recorrência semanal ou quinzenal. Quando você adicionar as matérias ao seu calendário você poderá ver que os eventos ocuparão o quadrimestre inteiro. Me avise se funcionar.

Quanto ao outro erro com o nome da disciplina realmente é algo que preciso resolver. Até o final da semana já devo ter uma atualização no sistema para isso e atualizo você por aqui.

**Comment by marcelojrfarias** [comment]
A questão do nome da matéria que continha dois pontos foi resolvida :)
