### ISSUE TITLE
Erro nome disciplina Interação Humano-Computador

### ISSUE THREAD

**Issue by matheusrod92** [marcelojrfarias/Calengrade#16]
**O QUE?**
A disciplina `Interação Humano-Computador` possui um hífen e apenas o que está após ele aparece como nome da disciplina no calendário.

**PREVIEW**
![image](https://user-images.githubusercontent.com/8302865/73850763-173dfd00-480b-11ea-9d41-6e7d9cc8a6bb.png)

**Comment by marcelojrfarias** [comment]
Resolvido :)
