### ISSUE TITLE
Aulas deslocadas

### ISSUE THREAD

**Issue by alinechan** [marcelojrfarias/Calengrade#3]
Usei o app em um MacOs e minhas aulas ficaram deslocadas em 1 dia, ou seja, as aulas de segunda ficaram no domingo, as de terca foram para segunda e assim sucessivamente.

Segue minha grade: 

ESTA020-17 - Modelagem e Controle A-Noturno (Santo André) - TPI (2 - 0 - 5) - Campus Santo André
Quarta-feira das 21:00 às 23:00 - semanal
ESTA023-17 - Introdução aos Processos de Fabricação A2-Noturno (Santo André) - TPI (3 - 1 - 4) - Campus Santo André
Quinta-feira das 19:00 às 21:00 - semanal
Terça-feira das 21:00 às 23:00 - semanal
ESTA014-17 - Sistemas CAD/CAM B2-Noturno (Santo André) - TPI (3 - 1 - 4) - Campus Santo André
Quinta-feira das 21:00 às 23:00 - semanal
Segunda-feira das 19:00 às 21:00 - semanal
ESTA004-17 - Circuitos Elétricos II A1-Noturno (Santo André) - TPI (3 - 2 - 4) - Campus Santo André
Quarta-feira das 18:00 às 21:00 - semanal
Segunda-feira das 21:00 às 23:00 - quinzenal (I)
Segunda-feira das 21:00 às 23:00 - quinzenal (II)

e a forma como ficou exibido no meu calendario: 
![Screen Shot 2020-01-10 at 16 11 03](https://user-images.githubusercontent.com/32132960/72303276-7dd85c80-364b-11ea-97d8-4a552d193da8.png)

**Comment by marcelojrfarias** [comment]
Fiz uma nova atualização. Por favor, repete o processo e vê se agora funciona.

**Comment by alinechan** [comment]
Depois da atualizacao funcionou certinho 

;)
