### ISSUE TITLE
Alertas

### ISSUE THREAD

**Issue by l1n3k3r** [marcelojrfarias/Calengrade#36]
Antes de tudo, parabéns pelo trampo.

Antes ele configurava o calendário com reminders, dessa vez não veio. Foi alguma alteração ou deu erro mesmo?

**Comment by marcelojrfarias** [comment]
@l1n3k3r era para estar funcionando! Quando você for gerar o próximo confirma por favor se está ok?

**Comment by marcelojrfarias** [comment]
Estou fechando por falta de resposta, mas qualquer coisa é só reabrir com as instruções de como reproduzir o problema :)
