### ISSUE TITLE
Matéria de segunda tá indo pro domingo

### ISSUE THREAD

**Issue by pedrolopes1** [marcelojrfarias/Calengrade#4]
Uso o Outlook para gerenciar minha agenda, e quando fiz a importação da agenda gerada, apenas a primeira aula da primeira segunda-feira ficou no dia certo, a recorrência das demais ficou tudo no domingo, mesmo quando abrindo o evento esteja lá como recorrência segunda-feira.

![Capture](https://user-images.githubusercontent.com/49045071/73386282-5f11d100-42ad-11ea-9c07-7a2b812b4c79.PNG)

Segue a grade:

BIR0603-15 - Ciência, Tecnologia e Sociedade A1-Noturno (Santo André) - TPI (3 - 0 - 4) - Campus Santo André
Quinta-feira das 19:00 às 21:00 - quinzenal (I)
Segunda-feira das 21:00 às 23:00 - semanal
ESZU034-17 - Ecologia do Ambiente Urbano A-Noturno (Santo André) - TPI (2 - 0 - 4) - Campus Santo André
Sexta-feira das 21:00 às 23:00 - semanal
BCN0407-15 - Funções de Várias Variáveis A4-Noturno (Santo André) - TPI (4 - 0 - 4) - Campus Santo André
Terça-feira das 19:00 às 21:00 - semanal
Quinta-feira das 21:00 às 23:00 - semanal
BCK0103-15 - Física Quântica S1-Noturno (Santo André) - TPI (3 - 0 - 4) - Campus Santo André
Quarta-feira das 19:00 às 21:00 - quinzenal (I)
MCTA022-13 - Redes de Computadores A2-Noturno (Santo André) - TPI (3 - 1 - 4) - Campus Santo André
Quarta-feira das 21:00 às 23:00 - semanal
Sexta-feira das 19:00 às 21:00 - quinzenal (I)
Sexta-feira das 19:00 às 21:00 - quinzenal (II)

**Comment by marcelojrfarias** [comment]
Olá, Pedro! Obrigado por sua contribuição :)

Eu fiz um teste com sua grade aqui no aplicativo de calendário do Windows 10 e ele carregou corretamente:

![image](https://user-images.githubusercontent.com/12167941/73408875-52f13800-42dc-11ea-97d5-0f4ae460a9d4.png)

Você poderia por favor enviar um print dos detalhes de um dos eventos que está no domingo? Como por exemplo:

![image](https://user-images.githubusercontent.com/12167941/73408906-68666200-42dc-11ea-9c12-0bdbe15c99f3.png)

Se possível, me fala também a versão do seu outlook por favor.

**Comment by marcelojrfarias** [comment]
Fiz uma nova atualização. Por favor, repete o processo e vê se agora funciona.

**Comment by pedrolopes1** [comment]
Show! Tudo certo
