### ISSUE TITLE
Opção de escolha do formato do calendário

### ISSUE THREAD

**Issue by soph-ramos** [marcelojrfarias/Calengrade#47]
Esse formato de calendário (.ics) é suportado somente pelo calendário do Windows. No Google Calendar - que apresenta muitas integrações possíveis com outros apps - o formato suportado é diferente (iCal ou CSV).  Tentei converter independentemente, mas não consegui.

**Comment by marcelojrfarias** [comment]
Oi! Na verdade o .ics que usamos deveria funcionar em todos os sistemas, dá uma checada.
