### ISSUE TITLE
Erro no deploy

### ISSUE THREAD

**Issue by mrsixx** [marcelojrfarias/Calengrade#63]
**O que?** 
Está rolando algum erro no deploy no heroku que impossibilita o uso do serviço.

**Preview** 
![image](https://user-images.githubusercontent.com/29840021/214096726-6c2e7843-fbc3-428a-a09e-949a0ff63af6.png)

**Comment by marcelojrfarias** [comment]
Eu estava hospedando no Heroku que era gratuito até ser comprado pela Sales Force. Acabei de ver que fecharam os serviços do site agora preciso hospedar em outro lugar.

**Comment by marcelojrfarias** [comment]
Esqueci de avisa, mas foi resolvido! Migrei tudo pro front e to rodando agora no Netlify :)

**Comment by mrsixx** [comment]
Valeu!
