### ISSUE TITLE
Integração Next + Calengrade

### ISSUE THREAD

**Issue by RicardoX2X** [marcelojrfarias/Calengrade#75]
Seria fantastico a integraçao do [Next](https://github.com/ufabc-next) com o Calengrade

**Comment by marcelojrfarias** [comment]
Seria né? Também acho! 💚

**Comment by marcelojrfarias** [comment]
Fala, @RicardoX2X! Boas notícias, agora é possível acessar o Calengrade dentro do UFABC Next: https://ufabcnext.com/app/calengrade ;)
